# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

security:
  providers:
    in_memory:
      memory:
        users:
          admin:
            password: $2y$12$jOsxedlvupodmOpJimlmm.1g7DPmxO91sDy7O5mA3iB6VEL0MW23C
            roles: 'ROLE_ADMIN'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    default:
      anonymous: ~
      http_basic: ~

  access_control:
    # require ROLE_ADMIN for /admin*
    - { path: ^/admin, roles: ROLE_ADMIN }

  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12
