# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  cake.admin.cake:
      class: CakeBundle\Admin\CakeAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Cake structure", label: "Cake" }
      arguments:
          - ~
          - CakeBundle\Entity\Cake
          - ~
      calls:
          - [ setTranslationDomain, [CakeBundle]]
  cake.admin.spongeType:
    class: CakeBundle\Admin\SpongeTypeAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Cake structure", label: "Spongecake" }
    arguments:
      - ~
      - CakeBundle\Entity\SpongeType
      - ~
    calls:
      - [ setTranslationDomain, [CakeBundle]]
  cake.admin.buttercream:
    class: CakeBundle\Admin\ButtercreamAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Cake structure", label: "Buttercream" }
    arguments:
      - ~
      - CakeBundle\Entity\Buttercream
      - ~
    calls:
      - [ setTranslationDomain, [CakeBundle]]
  cake.admin.frosting:
    class: CakeBundle\Admin\FrostingAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Cake structure", label: "Frosting" }
    arguments:
      - ~
      - CakeBundle\Entity\Frosting
      - ~
    calls:
      - [ setTranslationDomain, [CakeBundle]]
  cake.admin.soak:
    class: CakeBundle\Admin\SoakAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Cake structure", label: "Soak" }
    arguments:
      - ~
      - CakeBundle\Entity\Soak
      - ~
    calls:
      - [ setTranslationDomain, [CakeBundle]]
  cake.admin.order:
    class: CakeBundle\Admin\OrderAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Orders", label: "Order" }
    arguments:
      - ~
      - CakeBundle\Entity\Order
      - ~
    calls:
      - [ setTranslationDomain, [CakeBundle]]