# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    cake.admin.cake:
        class: CakeBundle\Admin\CakeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Cake structure", label: "Cake" }
        arguments:
            - ~
            - CakeBundle\Entity\Cake
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]
    cake.admin.spongeType:
            class: CakeBundle\Admin\SpongeTypeAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Cake structure", label: "Spongecake" }
            arguments:
                - ~
                - CakeBundle\Entity\SpongeType
                - ~
            calls:
                - [ setTranslationDomain, [AppBundle]]